block_lists:
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

blacklist:
  - "wpad.*"  # Web Proxy Auto-Discovery Protocol - minor speedup

dns_servers:
  - https://1.1.1.1/dns-query
  - dns+tls://1.0.0.1

listen_host: 127.0.0.1
