language: go
sudo: false

go:
  - "1.13"

cache:
  directories:
    - $GOPATH/pkg/mod

go_import_path: github.com/lietu/better-dns

env:
  - GO111MODULE=off

before_install:
  - mkdir -p $GOPATH/src/github.com/lietu/
  # Wtf Travis, is this really necessary?
  - ln -s $GOPATH/src/github.com/lietu/better-dns $TRAVIS_BUILD_DIR

# Skip Travis's automagic failures in dependency resolution
install: true

script:
  # - go test -race -v -bench=. -coverprofile=coverage.txt -covermode=atomic ./...

  - GOOS=windows GOARCH=amd64 go build -o better-dns-x86_64.exe better-dns.go
  - GOOS=windows GOARCH=386   go build -o better-dns-x86.exe    better-dns.g   o

  - mkdir -p artifacts
  - mv better-dns-x86_64.exe artifacts
  - mv better-dns-x86.exe artifacts

deploy:

  - provider: releases
    api_key: $GITHUB_TOKEN
    file: artifacts/*
    skip_cleanup: true
    prerelease: true
    on:
      branch: master

  - provider: releases
    api_key: $GITHUB_TOKEN
    file: artifacts/*
    skip_cleanup: true
    on:
      tags: true
