language: go
sudo: false

go:
  - "1.13"

cache:
  directories:
    - $GOPATH/pkg/mod

go_import_path: github.com/lietu/better-dns

git:
  depth: 10

# Skip Travis's automagic failures in dependency resolution
install:
  - go get github.com/akavel/rsrc
  - go get -u honnef.co/go/tools/cmd/staticcheck
  - go get -u github.com/kisielk/errcheck
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
  - errored=0
  - bash travis-build-better-dns-tray.sh
  - if [[ "$?" != "0" ]]; then errored=1; fi
  - bash travis-build-better-dns.sh
  - if [[ "$?" != "0" ]]; then errored=1; fi
  - bash travis-post-build.sh
  - if [[ "$?" != "0" ]]; then errored=1; fi
  - if [[ "$errored" != "0" ]]; then echo "Build failed."; exit 1; fi
  - export BODY=$(cat DESCRIPTION)

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    body: ${BODY}
    edge: true
    file: artifacts/*
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
